name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IS_PRERELEASE: "true"

jobs:
  build_artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Avoid shallow clone so we get our versioning correct.

      - name: Patch files
        run: |
          sh ./.build/create-build-artifacts.sh
          echo "NEXT_VERSION=$(cat .next-version)" >> $GITHUB_ENV

      - name: Create Release
        uses: meeDamian/github-release@2.0
        id: create_release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag: ${{ env.NEXT_VERSION }}
          name: v${{ env.NEXT_VERSION }}
          draft: false
          prerelease: ${{ env.IS_PRERELEASE }}
          files: ${{ env.NEXT_VERSION }}.tar.gz
          gzip: false
